package model;

public enum ContactType {
    MOBILE_PHONE_NUMBER,
    HOME_PHONE_NUMBER,
    EMAIL,
    SKYPE_LOGIN,
    LINKEDIN_PROFILE,
    GITHUB_PROFILE,
    STACKOVERFLOW_PROFILE,
    HOMEPAGE
}
